{% set name = "ngsidekick" %}
{% set version = "0.0.19" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/janelia-flyem/ngsidekick/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 9d5941d4b22ea9f21595507f7faf09003e25b6fb22c95eb03ea4af4d7ebfc77e

build:
  number: 0

  # Note: tensorstore isn't packaged for windows in conda-forge yet,
  # so this package will only work on mac/linux for now.
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling >=1.27
    - hatch-vcs
  run:
    - python >={{ python_min }}
    - numpy
    - pandas
    - pyarrow
    - duckdb
    - numba
    - tqdm
    - tensorstore
    - neuroglancer
    - requests
    - flask

test:
  imports:
    - ngsidekick
  requires:
    - python {{ python_min }}
    - pip
    - pytest
    - bokeh
  source_files:
    - tests
  commands:
    - pip check
    - pytest -ra -q -m 'not manual' tests

about:
  summary: Tools for preparing and working with neuroglancer scenes
  description: Tools for preparing and working with neuroglancer scenes.

  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

  home: https://github.com/janelia-flyem/ngsidekick
  dev_url: https://github.com/janelia-flyem/ngsidekick
  doc_url: https://janelia-flyem.github.io/ngsidekick/docs/index.html

extra:
  recipe-maintainers:
    - stuarteberg
